### ISSUE TITLE
Unexpected resulting links

### ISSUE THREAD

**Issue by jessogden** [edsu/unshrtn#11]
Hiya - 

I used unshrtn on a set of tweets collected with twarc that mostly contained Wayback links, but also included a number of t.cos and other links that I wanted to expand (and later count). 

It mostly worked a treat (yay!) apart from a few anomalies that showed up when I scanned the log that stripped some preceding bits in the link e.g. -

A few youtube links:

`https://web.archive.org/web/20111025035920/http://www.youtube.com/watch?v=B1zlool6Ia4&gl=US&hl=en -> /web/20111025035920/http://www.youtube.com/watch?v=B1zlool6Ia4`

`https://web.archive.org/web/20100807210813/http://www.youtube.com:80/user/thatsojack -> /web/20100807210813/http://www.youtube.com:80/user/thatsojack`

A link that shows up repeatedly in my dataset that doesn't have a http:// within the full Wayback link: 

`https://web.archive.org/web/20170929183546/committees.jsce.or.jp/eec2/node/108 -> /web/20170929183546/http://committees.jsce.or.jp/eec2/node/108`

But weirdly showed up later in the set, and worked as expected (e.g. no change):

`https://web.archive.org/web/20170929183546/committees.jsce.or.jp/eec2/node/108 -> https://web.archive.org/web/20170929183546/committees.jsce.or.jp/eec2/node/108`

Don't know if this is to be expected or even if it's possible to debug but thought I'd flag it up just the same. Happy to provide more info if need be

Thanks!

**Comment by edsu** [comment]
Thanks for this @jessogden. I recently split off the long url from the canonical link which accidentally reveals the problem:

```
{
  "short": "https://web.archive.org/web/20111025035920/http://www.youtube.com/watch?v=B1zlool6Ia4",
  "long": "https://web.archive.org/web/20111025035920/http://www.youtube.com/watch?v=B1zlool6Ia4",
  "canonical": "/web/20111025035920/http://www.youtube.com/watch?v=B1zlool6Ia4",
  "status": 200,
  "content_type": "text/html; charset=utf-8",
  "title": "\n        Jon Bellion performs 'Runway' outside Sullivan Hall in New York City\n      - YouTube\n  "
}
```

The canonical link is relative, even though the long url is correct. I need to make sure that canonical links include the full URL.

**Comment by edsu** [comment]
With [eb33fb66ecfea19] unshrtn will make sure canonical links are made absolute:

```
curl 'http://localhost:3000/?url=https://web.archive.org/web/20111025035920/http://www.youtube.com/watch?v=B1zlool6Ia4&gl=US&hl=en'
{
  "short": "https://web.archive.org/web/20111025035920/http://www.youtube.com/watch?v=B1zlool6Ia4",
  "long": "https://web.archive.org/web/20111025035920/http://www.youtube.com/watch?v=B1zlool6Ia4",
  "canonical": "https://web.archive.org/web/20111025035920/http://www.youtube.com/watch?v=B1zlool6Ia4",
  "status": 200,
  "content_type": "text/html; charset=utf-8",
  "title": "Jon Bellion performs 'Runway' outside Sullivan Hall in New York City - YouTube"
}
```

**Comment by jessogden** [comment]
Super cool, thanks @edsu
