### ISSUE TITLE
Switch to Travis CI's newer container-based infrastructure

### ISSUE THREAD

**Issue by eikeon** [edsu/unshrtn#5]
Might as well try it out: http://docs.travis-ci.com/user/workers/container-based-infrastructure/

**Comment by eikeon** [comment]
Switched in ffe2526b0e12922a27bd43d0c0858b6c7ff1633d – worked but actually took a bit longer than its been taking.

**Comment by edsu** [comment]
Longer isn't a problem, especially if it exercises the Dockerfile?

**Comment by eikeon** [comment]
It's not exercising the Dockerfile (Created issue #7), but looking for a way to exercise the Dockerfile is what caused this switch to pop back up on the radar.
