### ISSUE TITLE
Automated building of Dockerfile

### ISSUE THREAD

**Issue by eikeon** [edsu/unshrtn#7]
One way to test the Dockerfile is to automate build this way: http://docs.docker.com/docker-hub/builds/

**Comment by eikeon** [comment]
Since we don't have this automated yet I manually tested that the Dockerfile still builds and runs fine. Note node:latest is now version 0.12.0.

**Comment by edsu** [comment]
Seems to be [working](https://registry.hub.docker.com/u/edsu/unshrtn/) now! Not sure if there's a little badge that we can put in the README.md - at least I couldn't find one.

**Comment by eikeon** [comment]
Yeah, looks like there's no badges yet re: docker automated builds: badges/shields#241
